# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

app = angular.module('app', [])
app.controller 'CardsCtrl', [
  '$scope'
  ($scope) ->
    rank = undefined
    $scope.ranks = []
    $scope.ranks.push
      label: 'A'
      value: 1
    rank = 2
    while rank <= 10
      $scope.ranks.push
        label: rank
        value: rank
      rank += 1
    $scope.ranks.push
      label: 'J'
      value: 11
    $scope.ranks.push
      label: 'Q'
      value: 12
    $scope.ranks.push
      label: 'K'
      value: 13
    $scope.rank = $scope.ranks[0]
    $scope.suits = [
      {
        name: 'hearts'
        symbol: '♥'
      }
      {
        name: 'clubs'
        symbol: '♣'
      }
      {
        name: 'diamonds'
        symbol: '♦'
      }
      {
        name: 'spades'
        symbol: '♠'
      }
    ]
    $scope.suit = $scope.suits[0]
    return
]
app.directive 'playingCard', [ ->
  {
    replace: true
    templateUrl: 'playing-card'
    scope:
      rank: '='
      suit: '='
    link: ($scope, el$, attr) ->
      $scope.symbols = []
      $scope.isCourt = false

      $scope.updateSymbols = ->
        rank = undefined
        suit = undefined
        rank = $scope.rank
        suit = $scope.suit
        $scope.symbols = []
        if rank.value > 10
          $scope.isCourt = true
          $scope.symbols.push suit.symbol
        else
          while rank and $scope.symbols.length < rank.value
            $scope.symbols.push suit.symbol
        return

      $scope.$watch 'rank', $scope.updateSymbols
      $scope.$watch 'suit', $scope.updateSymbols
      return

  }
 ]

# ---
# generated by js2coffee 2.1.0